Bash/Zsh checkpoint, mostly related to Emacs & K8s

diff --git a/home/.zsh/aliases-common b/home/.zsh/aliases-common
--- a/home/.zsh/aliases-common
+++ b/home/.zsh/aliases-common
@@ -2,9 +2,41 @@
 # vim: set ft=sh:
 
 function have {
-    command -v "$1" >/dev/null
-    return $?
+    # command -v "$1" >/dev/null
+    /bin/whereis "$1" |awk '{print $2}' |/bin/grep -q '^/'
 }
+
+function inside-emacs {
+    [ -n "${INSIDE_EMACS}" ]
+}
+
+if inside-emacs; then
+    export PAGER=emacs-pager
+    alias less="${PAGER}"
+fi
+
+# Don't need this shim anymore because have emacs-pager-mode now.
+#
+# function bat {
+#     # must use abs path to bat(1) so we don't recurse!
+#     local bat_cmd="$(whereis -b bat |awk '{print $2}')"
+#
+#     if [ -z "${bat_cmd}" ]; then
+#         >&2 echo "$0: command not found: bat"
+#         return 127
+#     fi
+#     if inside-emacs; then
+#         # don't use pager
+#         "${bat_cmd}" -pp "$@"
+#     else
+#         "${bat_cmd}" "$@"
+#     fi
+# }
+
+if [ "$TERM" != dumb ]; then  # emacs sh-mode
+    have bat && alias cat=bat
+fi
+
 
 # aliases
 #
@@ -17,7 +49,14 @@ alias ad.='ls -ahF --color=auto -d .*'
 alias at='ls -ahF --color=auto -tr'
 alias as='ls -ahF --color=auto -Sr'
 
-if have 'ls++'
+alias aa='ls -ahF --color=auto -l'
+alias aa.='ls -ahF --color=auto -l .*'
+alias aad='ls -ahF --color=auto -l -d'
+alias aad.='ls -ahF --color=auto -l -d .*'
+alias aat='ls -ahF --color=auto -l -tr -L'  # deref symlinks
+alias aas='ls -ahF --color=auto -l -Sr -L'  #
+
+if have 'ls++' && ! inside-emacs
 then
     alias aa='ls++ --potsf -a'
     alias aa.='ls++ --potsf -a .*'
@@ -27,13 +66,6 @@ then
     alias aas='ls++ --potsf -a -Sr'
     alias aaat='ls++ --potsf -a -tr -L'  # deref symlinks
     alias aaas='ls++ --potsf -a -Sr -L'  #
-else
-    alias aa='ls -ahF --color=auto -l'
-    alias aa.='ls -ahF --color=auto -l .*'
-    alias aad='ls -ahF --color=auto -l -d'
-    alias aad.='ls -ahF --color=auto -l -d .*'
-    alias aat='ls -ahF --color=auto -l -tr -L'  # deref symlinks
-    alias aas='ls -ahF --color=auto -l -Sr -L'  #
 fi
 
 alias wa='sudo ls -ahF --color=auto'
@@ -73,24 +105,28 @@ alias 7='pushd +7'
 alias 8='pushd +8'
 alias 9='pushd +9'
 
-have bat && alias cat=bat
-have egrep && alias grep='egrep --color=auto'
 have colordiff && alias diff=colordiff
 have lftp && alias ftp=lftp
 alias gdb='gdb -q'
 
-if have vim; then
-    alias vi=vim
-    alias ivm=vim
-    alias wv='sudo vim'
+if ! inside-emacs; then
+    if have vim; then
+        alias vi=vim
+        alias ivm=vim
+        alias wv='sudo vim'
+    else
+        alias ivm=vi
+        alias wv='sudo vi'
+    fi
+    alias v=vi
+    alias vv='vi ~/.vimrc'
+    alias vh='vi /etc/hosts'
+    alias vssh='vi ~/.ssh/config'
 else
-    alias ivm=vi
-    alias wv='sudo vi'
+    alias vi=emacsclient
+    alias vim=emacsclient
 fi
-alias v=vi
-alias vv='vi ~/.vimrc'
-alias vh='vi /etc/hosts'
-alias vssh='vi ~/.ssh/config'
+
 #alias find-vim-swaps="find -L . -type f -name '.*.sw[pon]'"
 function find-vim-swaps {
     local dir=~/.cache/vim/swap
@@ -132,30 +168,164 @@ alias untarxz='tar xvJf'
 alias n='sudo lsof -Pni 2>/dev/null |grep LIST'
 alias td='sudo tcpdump -nn'
 
+alias grep='grep -E --color=auto'
 alias gr='grep -RIi --color --exclude-dir=.git --exclude-dir=.tox'
 alias wgr='sudo grep -RIi --color --exclude-dir=.git --exclude-dir=.tox'
 
 if have rg; then
     alias gr=rg
-    alias gri='gr --ignore'  # honor .gitignore
+    alias grq='gr --no-filename --no-heading --no-line-number'  # STFU
+    alias gri='gr --ignore'  # use .gitignore patterns
+    alias griq='grq --ignore'
     alias wgr='sudo rg'
     alias wgri='wgr --ignore'
 fi
 
-function t { local p="${1:-.}"; find "$p" -path .git -o -path .tox -prune -o -print; }
-have tree && alias t='tree -aCI .git\|.tox'
-have tree && alias tt='tree -apDFhCI .git\|.tox'
+if have tree; then
+    alias t='tree -aCI .git\|.tox'
+    alias tt='tree -apDFhCI .git\|.tox'
+else
+    function t {
+        local p="${1:-.}"
+        find "$p" -path .git -o -path .tox -prune -o -print
+    }
+fi
 
 alias ww=~/g2sh.pl
 alias r2='ssh -l root'
 alias j='journalctl -xab |less +G'
 alias jf='journalctl -xfab'
+alias ju='journalctl -u'
+alias juu='journalctl --user -u'
 alias uf='systemctl list-unit-files'
+alias uuf='systemctl list-unit-files --user'
 alias tf='tail -f'
 alias wtf='sudo tail -f'
 alias tmm='tmux ls'
-alias tma='tmux attach'
+inside-emacs || alias tma='tmux attach'
 alias be='bundle exec'
+
+alias k=kubectl
+alias kar='k api-resources |sort'
+alias kav='k api-versions |sort'
+alias kaf='k apply -f'
+alias kdf='k diff -f'
+alias kpf='k port-forward'
+
+kubectl_get_nodes_by_inst() {
+    local type="$1"
+    if [ -z "$type" ]; then
+        >&2 echo "usage: kgni {INSTANCE_TYPE}"
+        >&2 echo "1 argument expected, received 0."
+        return 1
+    fi
+    kubectl get nodes -l node.kubernetes.io/instance-type="$type"
+}
+
+kubectl_get_pods_by_node() {
+    local node="$1"
+    if [ -z "$node" ]; then
+        >&2 echo "usage: kgpn {NODE}"
+        >&2 echo "1 argument expected, received 0."
+        return 1
+    fi
+    kubectl get pods -A --field-selector spec.nodeName="$node" -o wide \
+        |awk '{NF-=2}1' \
+        |awk '(NR==1){NF-=2;print}(NR!=1)' \
+        |column -t
+}
+#export -f kubectl_get_pods_by_node
+
+# kubectl get
+alias kg='k get'
+alias kgr='k get --raw'
+alias kgw='k get -w'
+alias kga='k get all'
+alias kgaa='k get all -A'
+alias kgn='kg node'
+alias kgnw='kgw node'
+alias kgni='kubectl_get_nodes_by_inst'
+alias kgns='kg namespace'
+alias kgsa='kg serviceaccount'
+alias kgcm='kg configmap'
+alias kgt='kg secret'
+alias kgds='kg daemonset'
+alias kgdsw='kgw daemonset'
+alias kgrs='kg replicaset'
+alias kgrsw='kgw replicaset'
+alias kgsts='kg statefulset'
+alias kgstsw='kgw statefulset'
+alias kgd='kg deployment'
+alias kgdw='kgw deployment'
+alias kgp='kg pods'
+alias kgpw='kgw pods'
+alias kgpa='kgp -A'
+alias kgpn='kubectl_get_pods_by_node'
+alias kgs='kg service'
+alias kgsw='kgw service'
+alias kgi='kg ingress'
+alias kgiw='kgw ingress'
+alias kgpv='kg pv'
+alias kgpvc='kg pvc'
+alias kgpvcw='kgw pvc'
+alias kgep='kg endpoints'
+alias kgepw='kgw endpoints'
+alias kges='kg es'
+alias kgesa='kg es -A'
+alias kgesaw='kgw es -A'
+alias kgmp='kg meshpolicy'
+alias kgmw='kg mutatingwebhookconfigurations'
+alias kgoc='kg otelcol'
+
+# kubectl describe
+alias kd='k describe'
+alias kdn='kd node'
+alias kdns='kd namespace'
+alias kdsa='kd serviceaccount'
+alias kdcm='kd configmap'
+alias kdt='kd secret'
+alias kdds='kd daemonset'
+alias kdrs='kd replicaset'
+alias kdsts='kd statefulset'
+alias kdd='kd deployment'
+alias kdp='kd pod'
+alias kds='kd service'
+alias kdpv='kd pv'
+alias kdpvc='kd pvc'
+alias kdep='kd endpoints'
+alias kdes='kd es'
+alias kdmp='kd meshpolicy'
+alias kdmw='kd mutatingwebhookconfigurations'
+alias kdoc='kd otelcol'
+
+# kubectl edit
+alias ke='k edit'
+alias kesa='ke serviceaccount'
+alias kecm='ke configmap'
+alias ket='ke secret'
+alias ked='ke deployment'
+alias keds='ke daemonset'
+alias kers='ke replicaset'
+alias kests='ke statefulset'
+alias kep='ke pod'
+alias kes='ke service'
+alias keoc='ke otelcol'
+
+# kubectl scale
+alias ksd='kubectl scale deploy --replicas'
+
+# kubectl exec
+alias kit='k exec -it'
+
+# kubectl logs
+alias kl='k logs'
+
+# kubectl config
+alias kcc='k config get-contexts'
+alias kuc='k config use-context'
+alias kn='k config set-context --current --namespace'
+
+alias nat='sudo iptables -L -n -t nat'
 
 if command dmesg -V 2>&1 |grep -q 'invalid option'; then
     # XXX which version of util-linux introduced `-H'?  same one as `-V'?!
@@ -180,5 +350,3 @@ elif grep -iwq arch /etc/issue; then
     alias show='pacaur -Si'
     alias pmi='pacaur -S'
 fi
-
-unset -f have
